### ISSUE TITLE
 attempt to index field 'task' (a nil value)

### ISSUE THREAD

**Issue by mycf** [dasupradyumna/launch.nvim#3] opened 2023-11-22 13:26 UTC
run LaunchOpenConfigFile and got this
```

Error executing Lua callback: ...l/share/nvim-custom/lazy/launch.nvim/lua/launch/view.lua:38: attempt to index field 'task' (a nil value)
stack traceback:
	...l/share/nvim-custom/lazy/launch.nvim/lua/launch/view.lua:38: in function '__index'
	...share/nvim-custom/lazy/launch.nvim/lua/launch/config.lua:108: in function 'open_file'
	...cal/share/nvim-custom/lazy/launch.nvim/plugin/launch.lua:19: in function <...cal/share/nvim-custom/lazy/launch.nvim/plugin/launch.lua:19>
```

**Comment by dasupradyumna** [comment] 2023-11-22 15:50
I am unable to reproduce this issue (both with and without lazy-loading).

Can you share your plugin setup for **launch.nvim** and also the exact steps to reproduce the bug?

**Comment by dasupradyumna** [comment] 2023-12-27 07:11
Closing due to lack of user response.
Reopen when needed.

**Closed by dasupradyumna** 2023-12-27 07:11 UTC
